version: '3.8'

services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=qbox
    labels:
      org.springframework.boot.ignore: true

  redis:
    image: redis:latest
    restart: always
    environment:
      - TZ=Asia/Seoul
    ports:
      - "6379:6379"
    labels:
      org.springframework.boot.ignore: true

#  prometheus:
#    image: prometheus:latest
#    ports:
#      - "9090:9090"
#    volumes:
#      - ./prometheus.yml:/etc/prometheus/prometheus.yml
#    command:
#      - '--config.file=/etc/prometheus/prometheus.yml'
#
#  grafana:
#    image: grafana
#    depends_on:
#      - prometheus
#    volumes:
#      - ./grafana-datasource.yml:/etc/grafana/provisioning/grafana-datasource.yml
#    ports:
#      - "3000:3000"