server:
  servlet:
    context-path: /api
    session:
      cookie:
        secure: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  security:
    allow-origins: ${ALLOW_ORIGINS}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_ID}
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  data:
    redis:
      url: redis://localhost:6379
logging:
  slack:
    webhook-uri: http://localhost:1234
  config: classpath:logback-spring.xml

service:
  url: http://localhost:5172

local-storage:
  directory: http://localhost/qbox/image/
  url: http://localhost:5172


management:
  endpoints:
    enabled-by-default: false
    jmx:
      exposure:
        exclude: *
    web:
      exposure:
        include: prometheus
      base-path: /actuator
  server:
    port: 8081
